version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/proj
      # - /proj/bin  # To not overwrite file modes.
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
