name: dinora_chess
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pydantic=1.10.*
  - lightning
  - wandb
  - tqdm
  - pytorch
  - pytorch-cuda
  - matplotlib
  - notebook

  # Visualizations
  - pillow
  - cairosvg
  - python-graphviz

  - pip
  - pip:
      - -e .
      - chess
      - pylru
      - click
      # documentation
      - Sphinx
      - furo
      # tests
      - pytest
      - pytest-cov
      - pytest-benchmark
      # devtools
      - pre-commit
      - black
      - mypy
