name: dinora_chess
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - lightning
  - pydantic=1.10.*  # Don't use pydantic in dinora, this is for lightning
  - wandb
  - tqdm
  - pytorch
  - pytorch-cuda
  - matplotlib
  - notebook

  # Visualizations
  - pillow
  - cairosvg
  - python-graphviz

  - pip
  - pip:
      - -e .
      - chess
      - pylru
      # documentation
      - Sphinx
      - furo
      # tests
      - pytest
      - pytest-cov
      # devtools
      - pre-commit
      - black
      - mypy
