name: dinora
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - lightning
  - wandb
  - tqdm
  - pytorch=2.0.0=py3.10_cuda11.8_cudnn8_0
  - matplotlib
  - notebook
  
  # Visualizations
  - pillow
  - cairosvg
  - python-graphviz

  - pip
  - pip:
      - -e .
      # TODO migrate fully to torch and remove tf
      - tensorflow<2.11
      - tensor-annotations
      - tensor-annotations-tensorflow-stubs
      - chess
      - pylru
      - click
      # documentation
      - Sphinx
      - furo
      # tests
      - pytest
      - pytest-cov
      - pytest-benchmark
      # devtools
      - pre-commit
      - black
      - mypy
