[tool.poetry]
name = "Dinora"
version = "0.1.0"
description = "Chess Engine"
authors = ["Saegl <saegl@protonmail.com>"]
license = "GPL v3"

[tool.poetry.dependencies]
python = "^3.9"
tensorflow = "^2.5.0"
numpy = "^1.21.1"
chess = "^1.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
