[tool.poetry]
name = "Dinora"
version = "0.1.2"
description = "Chess Engine"
authors = ["Saegl <saegl@protonmail.com>"]
license = "GPL v3"
include = ['models/best_model.h5']

[tool.poetry.dependencies]
python = "^3.7"
tensorflow = "^2.5.0"
numpy = "^1.19.2"
chess = "^1.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
