[tool.poetry]
name = "Dinora"
version = "0.0.1"
description = "Dinora Chess Engine"
authors = ["Saegl <saegl@protonmail.com>"]
license = "GPL v3"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
tensorflow = "2.8.0"
numpy = "^1.19.2"
chess = "^1.6.1"
pylru = "^1.2.0"
pre-commit = "^2.19.0"
pytest = "^7.1.2"

[tool.poetry.dev-dependencies]
black = {version = "^22.3.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["."]
