[tool.poetry]
name = "Dinora"
version = "0.5"
description = "Chess Engine"
authors = ["Saegl <saegl@protonmail.com>"]
license = "GPL v3"
include = ['models/best_model.h5']

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
tensorflow = "2.8.0"
numpy = "^1.19.2"
chess = "^1.6.1"
pylru = "^1.2.0"

[tool.poetry.dev-dependencies]
black = {version = "^21.7b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
